#!/usr/bin/env python3
"""Generate pdf_sign.cil: a copy of container_t plus Wayland access.

Reads `sesearch` output for the loaded policy on stdin sections and prints a
CIL module defining pdf_sign_t with every attribute, unconditional allow rule
and type transition that the policy grants container_t by name, followed by
the two permissions a Wayland client needs.

Run through ./generate.sh, which feeds it from the host's loaded policy.
"""

import re
import sys

SRC = "container_t"
NEW = "pdf_sign_t"


def sub(t):
    return NEW if t == SRC else t


def main():
    text = sys.stdin.read()
    sections = dict(
        re.findall(r"^### (\w+)\n(.*?)(?=(?:^### )|\Z)", text, re.DOTALL | re.MULTILINE)
    )

    attrs = []
    m = re.search(r"type container_t(?: alias [^,]+)?,(.*)", sections["attributes"])
    if m:
        attrs = [a.strip(" ;") for a in m.group(1).split(",") if a.strip(" ;")]

    allows = []
    for line in sections["allow"].splitlines():
        line = line.strip()
        if not line.startswith(f"allow {SRC} ") or line.endswith("True") or "[" in line:
            continue  # rules for attributes apply already; skip boolean-gated ones
        m = re.match(r"allow (\S+) ([^\s:]+):(\S+) (?:\{ ([^}]*) \}|([^\s;]+));$", line)
        if not m:
            sys.exit(f"cannot parse: {line}")
        _, tgt, cls, many, one = m.groups()
        perms = many.split() if many else [one]
        allows.append(f"(allow {NEW} {sub(tgt)} ({cls} ({' '.join(perms)})))")

    transitions = []
    for line in sections["transition"].splitlines():
        line = line.strip()
        if not line.startswith(f"type_transition {SRC} "):
            continue
        m = re.match(
            r"type_transition (\S+) ([^\s:]+):(\S+) ([^\s;]+)(?: ([^\s;]+))?;$", line
        )
        if not m:
            sys.exit(f"cannot parse: {line}")
        _, tgt, cls, result, name = m.groups()
        name_part = f' "{name}"' if name else ""
        transitions.append(
            f"(typetransition {NEW} {sub(tgt)} {cls}{name_part} {sub(result)})"
        )

    print(f"""; SELinux type for the pdf-sign Reader container. GENERATED by generate.sh
; from the loaded policy ({sections["versions"].strip()}); do not edit.
;
; pdf_sign_t is container_t (same attributes, and a copy of every
; unconditional rule the policy grants container_t by name), plus what a
; Wayland client needs: write to the compositor's socket file (user_tmp_t),
; connect to the compositor (gnome-shell runs as unconfined_t), and use the
; shared-memory files it passes back. The container's filesystem only
; exposes the Wayland socket, so that is all these rules make reachable.
;
; Install:  sudo semodule -i selinux/pdf_sign.cil   (make selinux)
; Remove:   sudo semodule -r pdf_sign

(type {NEW})
(roletype system_r {NEW})""")
    for a in attrs:
        print(f"(typeattributeset {a} ({NEW}))")
    print("\n; Rules the policy grants container_t by name")
    print("\n".join(allows))
    print("\n; File labeling inside the container, as for container_t")
    print("\n".join(transitions))
    print(f"""
; Run by rootless podman, as for udica-generated container types
(allow container_runtime_t {NEW} (key (create link read search setattr view write)))

; Wayland: the compositor's socket, and the shared-memory files (keymap)
; the compositor passes over it. Only the socket is mounted, so user_tmp_t
; files reach the container only when the compositor hands them over.
(allow {NEW} user_tmp_t (sock_file (getattr write)))
(allow {NEW} unconfined_t (unix_stream_socket (connectto)))
(allow {NEW} user_tmp_t (file (getattr read write map)))""")


if __name__ == "__main__":
    main()
